### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by tchoutri** [gombocarti/erlang-ffi#4]
Hi! I tried to run the example code, and while everything compiles well, I get a funny error in my erlang console when starting `Hello`:

```
=ERROR REPORT==== 29-Jan-2017::15:22:09 ===
** Connection attempt from disallowed node haskell@localhost **
```

Then in the other terminal, the binary tells me

```
Hello: Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
Hello: thread blocked indefinitely in an MVar operation
```

Do you have any kind of ideas about that?

**Comment by poor-a** [comment]
Hi!
Typically, this error arises when the secret cookies of the nodes differ. Check your `.erlang.cookie` files.

**Comment by tchoutri** [comment]
@poor-a hi! Well, now I'm embarassed because I run both programs on localhost :s

**Comment by tchoutri** [comment]
@poor-a could you confirm that it still works on your machine? =)

**Comment by poor-a** [comment]
Well, that is interesting. Perhaps the cookie file consists of two lines (the string with a newline character at the end)?

**Comment by tchoutri** [comment]
oh indeed, I think there's a `\n` at the end!

**Comment by poor-a** [comment]
Great! I will make the code less sensitive to newline characters.

**Comment by tchoutri** [comment]
I removed it and generated another one (by the VM, not by myself).
I'll tell you if it works now :)
@poor-a fantastic, it works :D
